[pre-push-readme-usage] fix: shellcheck fixes for POSIX sh

diff --git a/git_hooks/scripts/hooks/pre-push-readme-usage b/git_hooks/scripts/hooks/pre-push-readme-usage
--- a/git_hooks/scripts/hooks/pre-push-readme-usage
+++ b/git_hooks/scripts/hooks/pre-push-readme-usage
@@ -1,5 +1,8 @@
 #!/bin/sh
 # Automatically update README ## Usage
+# shellcheck disable=SC2059 # do not use variables in the printf format string.
+## shellcheck disable=SC2034 # appears unused
+
 
 # if any command inside script returns error, exit and return that error
 #set -e
@@ -9,56 +12,62 @@ msg='readme usage updated.'
 
 # colors example
 # printf "%s\n" "Text in ${red}red${end}, white and ${blu}blue${end}."
-red=$'\e[1;31m'
-grn=$'\e[1;32m'
-yel=$'\e[1;33m'
-blu=$'\e[1;34m'
-mag=$'\e[1;35m'
-cyn=$'\e[1;36m'
-end=$'\e[0m'
+red="\033[1;31m"
+grn="\033[1;32m"
+yel="\033[1;33m"
+blu="\033[1;34m"
+mag="\033[1;35m"
+cyn="\033[1;36m"
+end="\033[0m"
 
-branch="$(git rev-parse --abbrev-ref HEAD)"
-root_dir=$(r=$(git rev-parse --show-toplevel) && ([[ -n $r ]] && echo "$r" || (cd $(git rev-parse --git-dir)/.. && pwd) ))
+get_git_root_dir() {
+    gitdir=$(git rev-parse --show-toplevel)
+    [ -d "$gitdir" ] || exit 3
+    echo "$gitdir"
+}
 
 edit_readme_usage() {
-    cd "$root_dir"
-    README="$(ls | grep -i readme*)"
-    PROGRAM="$(ls | grep -i "$program_name")"
-    readonly temp_usage='.usage'
-    # output help and replace all tabs in "$temp_usage" with 4 spaces
-    COMMAND="$(./"$PROGRAM" -h| expand -t 4 > "$temp_usage")"
+    grd=$(get_git_root_dir)
+    cd "$grd" || exit 2
+    grd_files=$(find "$grd" -maxdepth 1 -type f -printf '%f\n')
+    README_NAME=$(echo "$grd_files" | grep -i readme | head -n1)
+    PROGRAM_NAME=$(echo "$grd_files" | grep -i "$program_name" | head -n1)
+    # output help and replace all tabs in temp file with 4 spaces
+    COMMAND_OUT=$("./$PROGRAM_NAME" -h | expand -t4)
+    tmp_file="/tmp/readme_usage.txt"
+    echo "$COMMAND_OUT" > "$tmp_file"
     # skip over the lines with /n and delete in between
     sed -i '
         /## Usage/,/```$/ {
             /## Usage/n
             /```/!d
         }
-    ' $README
+    ' "$README_NAME"
     # append text from a file after the pattern
     sed -i '
         /## Usage/,/```$/ {
-            /```..*/r '"${temp_usage}"'
+            /```..*/r '"${tmp_file}"'
         }
-    ' $README
+    ' "$README_NAME"
     # remove temp file at the end
-    rm -rf "$temp_usage"
+    rm -rf "$tmp_file"
     # show message
     printf "${cyn}...HOOK...${end}${yel}${0}:${end} ${msg}\n"
 }
 
 check_readme_modification() {
-    # cancel push if README has not staged changes
-    CHECK_M="$(git status --porcelain| grep -i "$README")"
-    return_code=$?
-    if [ ! "$return_code" -ne 0 ]; then
-        printf "${red}ABORT ${README} has not staged changes.${end}\n"
-        printf "${cyn}Stage ${README}${end} and add it to commit first.${end}\n"
+    # cancel push if README_NAME has not staged changes
+    if git status --porcelain | grep -iq "$README_NAME"; then
+        printf "${red}ABORT ${README_NAME} has not staged changes.${end}\n"
+        printf "${cyn}Stage ${README_NAME}${end} and add it to commit first.${end}\n"
         exit 1 # if you remove this line then it won't block push
     fi
 }
 
+grd=$(get_git_root_dir) # check if git dir
+branch="$(git rev-parse --abbrev-ref HEAD)"
 # a branch name where you want to prevent git push. In this case, it's "master"
-if [[ "$branch" == master ]]; then
+if [ "$branch" = master ]; then
     # DO THINGS HERE
     edit_readme_usage
     check_readme_modification
