[setbg] shellcheck fixes, general improvements

diff --git a/sh/img/setbg b/sh/img/setbg
--- a/sh/img/setbg
+++ b/sh/img/setbg
@@ -1,49 +1,57 @@
-#!/bin/sh
-DEST_PATH="$HOME/.config/wallpaper.jpg"
+#!/bin/bash
+# advanced wallpaper setter
+# with support of 'magick convert' options without modifying original image
+
+XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"
+XDG_CACHE_HOME="${XDG_CACHE_HOME:-"$HOME/.cache"}"
+
+CSCRDIR="${CSCRDIR:-"$XDG_CACHE_HOME/cscripts"}"
+[ ! -d "$CSCRDIR" ] && mkdir -p "$CSCRDIR"
+
+DEST_PATH="$XDG_CONFIG_HOME/wallpaper.jpg"
 CACHE="$CSCRDIR/setbg"
-C_MCT=$(cat "$CACHE" | awk 'NR==1' | grep -o "[01]") # get MCT flag from cache
+
+# get options saved in cache
+C_MCT=$(awk 'NR==1' "$CACHE" | grep -o "[01]")
 C_XARGS=$(sed -n "/(/,/)/p" "$CACHE" | sed '1d;$d')
 C_MARGS=$(sed -n "/{/,/}/p" "$CACHE" | sed '1d;$d')
+
 ST_S="string:x-dunst-stack-tag:setbg"
 ST_H="string:x-dunst-stack-tag:hi" # history_ignore
 
+bname="$(basename "$0")"
 USAGE=$(printf "%s" "\
-Usage: $(basename "$0") [OPTION...]
+Usage: $bname [OPTION...]
 OPTIONS
     -c, --clear-margs       Clear magick convert arguments
     -h, --help              Display help
     -i, --image             Provide wallpaper image
     -m, --margs             Use 'magick convert' arguments specified 'inside single quotes'
     -x, --xargs             Set 'xwallpaper' options
-    --magic-combine-toggle  Toggle combining of magic convert options and exit
+    --mct                   Toggle combining of magick convert options and exit
     --outint                Set output name by num from '1' to 'N' connected outputs
     --outname               Set output name with grep -i like 'VGA', first found if many
     --startup               Set default wallpaper image and exit without magick
 EXAMPLES
-    $(basename "$0") -i image.jpg -x '--maximize' --margs='-colorspace Gray'
-    # and to clear margs cache
-    $(basename "$0") -i image.jpg --margs=''
+    $bname -i ./image.jpg -x '--maximize' --margs='-colorspace Gray'
 ")
+
+at_path() { hash "$1" >/dev/null 2>&1 ;} # if $1 is found at $PATH -> return 0
 
 get_opt() {
     # Parse and read OPTIONS command-line options
     SHORT=chi:m:x:
-    LONG=clear-margs,help,image:,margs:,xargs:,magic-combine-toggle,outint:,outname:,startup
+    LONG=clear-margs,help,image:,margs:,xargs:,mct,outint:,outname:,startup
     OPTIONS=$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")
     # PLACE FOR OPTION DEFAULTS
-    xargs_array=(${C_XARGS}); [ -z "$xargs_array" ] && xargs_array=('--zoom') # if C_XARGS empty
-    margs_array=(${C_MARGS}) # get 'magick convert' args from cache
+    # get xwallpaper & 'magick convert' args from cache
+    IFS=" " read -r -a xargs_array <<< "$C_XARGS"
+    IFS=" " read -r -a margs_array <<< "$C_MARGS"
+    [ -z "${xargs_array[*]}" ] && xargs_array=( --zoom )
     MCT=${C_MCT:-0}
     output='all'
     # decide which image file to work with (--image option override this)
-    if [ "$#" -gt 0 ]; then
-        image="${*: -1}" # get last element from arguments
-    elif test ! -t 0; then
-        image=$(cat) # /dev/stdin pipe used usually
-        [ ! -e "$image" ] && echo "file taken from -in, does not exist. exit." && exit 1
-    else
-        [ -f "$DEST_PATH" ] && image="$DEST_PATH" # get default image if file exist
-    fi
+    [ -e "$DEST_PATH" ] && image="$DEST_PATH" # get default image if file exist
     eval set -- "$OPTIONS"
     while true; do
         case "$1" in
@@ -61,19 +69,21 @@ get_opt() {
         -m|--margs)
             shift
             if [ "$MCT" -eq 1 ]; then
-                margs_array=( ${margs_array[@]} $1)
+                IFS=" " read -r -a margs_array <<< "${margs_array[*]} $1"
             else
-                margs_array=($1)
+                IFS=" " read -r -a margs_array <<< "$1"
             fi
             ;;
         -x|--xargs)
             shift
-            xargs_array=($1)
+            IFS=" " read -r -a xargs_array <<< "$1"
             ;;
-        --magic-combine-toggle)
+        --mct)
             [ "$MCT" -eq 1 ] && MCT=0 || MCT=1 # toggle behavior of value
             COMBINE_TOGGLED=1 # flag -> basically check if this variable defined
-            dunstify -u low -h "$ST_S" -h "$ST_H" "[setbg] MCT=$MCT" ""
+            if at_path dunstify; then
+                dunstify -u low -h "$ST_S" -h "$ST_H" "[setbg] MCT=$MCT" ""
+            fi
             ;;
         --outint)
             shift
@@ -84,7 +94,12 @@ get_opt() {
             output=$(xrandr -q | grep -i ' connected' | awk '{print $1}' | grep -i "$1" | awk 'NR==1')
             ;;
         --startup)
-            xwallpaper --output "$output" "${xargs_array[@]}" "$DEST_PATH"
+            if at_path xwallpaper; then
+                xwallpaper --output "$output" "${xargs_array[@]}" "$DEST_PATH"
+            else
+                echo "xwallpaper not found at path!"
+                exit 1
+            fi
             exit 0
             ;;
         --)
@@ -98,26 +113,34 @@ get_opt() {
 
 get_opt "$@"
 
-read -d '' cache <<- EOF
+cache=$(printf "%s" "\
 $MCT
 (
-${xargs_array[@]}
+${xargs_array[*]}
 )
 {
-${margs_array[@]}
+${margs_array[*]}
 }
-EOF
+")
 
 echo "$cache" > "$CACHE" # write to cache
 [ "$COMBINE_TOGGLED" ] && exit 0
 
-if [ -n "${margs_array[*]}" ]; then
-    printf "magick convert (args):\n%s\n" "${margs_array[*]}"
-    dunstify -u low -h "$ST_S" -h "$ST_H" "[setbg] MCT=$MCT margs:" "\n${margs_array[*]}\n"
+# image magick convert ($ magick -list tool)
+if at_path magick && [ -n "${margs_array[*]}" ]; then
     magick convert "$image" "${margs_array[@]}" "$DEST_PATH"
+    if at_path dunstify; then
+        dunstify -u low -h "$ST_S" -h "$ST_H" "[setbg] MCT=$MCT margs:" "\n${margs_array[*]}\n"
+    else
+        printf "MCT=$MCT magick convert (args):\n%s\n" "${margs_array[*]}"
+    fi
 elif [ -n "$image" ]; then
     cp "$image" "$DEST_PATH"
 fi
-wait
 
-xwallpaper --output "$output" "${xargs_array[@]}" "$DEST_PATH"
+if at_path xwallpaper; then
+    xwallpaper --output "$output" "${xargs_array[@]}" "$DEST_PATH"
+else
+    echo "xwallpaper not found at path!"
+    exit 1
+fi
